create table public.profile (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  first_name character varying not null,
  last_name character varying not null,
  email character varying not null,
  avatar character varying null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  dob date null,
  username character varying not null,
  constraint profile_pkey primary key (id)
) TABLESPACE pg_default;

-- DROP TRIGGER on_auth_user_created ON auth.users;
-- DROP FUNCTION public.handle_new_user();

-- inserts a row into public.profile
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profile (user_id, first_name, last_name, email, avatar, dob, username)
  values (new.id, new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name', new.email, new.raw_user_meta_data ->> 'avatar', new.raw_user_meta_data ->> 'date_of_birth', new.raw_user_meta_data ->> 'username');
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();